unbind C-b
set -g prefix C-\\
set -g default-shell /bin/fish

# This is for vim to handle focus change
set -g focus-events on

unbind r
bind r source-file ~/.tmux.conf \; display "Reloaded ~/.tmux.conf"

# panes remaps
# reasonable splitting
unbind %
unbind \"
bind v split-window -h -c "#{pane_current_path}"
bind h split-window -v -c "#{pane_current_path}"
# killing pane without confirm
unbind x
bind x kill-pane

# Sessions
bind k confirm-before -p "kill-session #S? (y/n)" kill-session

# moving between keys
bind -n m-h select-pane -L
bind -n m-l select-pane -R
bind -n m-j select-pane -D
bind -n m-k select-pane -U

# resizing panes
bind -n M-H resize-pane -L 1
bind -n M-L resize-pane -R 1
bind -n M-J resize-pane -D 1
bind -n M-K resize-pane -U 1

# copy mode
set-window-option -g mode-keys vi
unbind c
bind-key c copy-mode
unbind -T copy-mode-vi Enter
bind-key -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel 'wl-copy'
# windows
bind-key w new-window -c "#{pane_current_path}"

bind-key e display-popup -E 'bpython'
bind-key a display-popup -E 'fish'

# Looks

# Random lines from intnet that fix them inside vim
# https://superuser.com/questions/1266585/vim-color-scheme-does-not-work-in-tmux
set -g default-terminal screen-256color
# set -g terminal-overrides ',screen-256color:Tc'
set -ga terminal-overrides ",*256col*:Tc"
# below is tmux-gruvbox dark: https://github.com/egel/tmux-gruvbox
set-option -g status "on"

# default statusbar color
set-option -g status-style bg=colour237,fg=colour223 # bg=bg1, fg=fg1

# default window title colors
set-window-option -g window-status-style bg=colour214,fg=colour237 # bg=yellow, fg=bg1

# default window with an activity alert
set-window-option -g window-status-activity-style bg=colour237,fg=colour248 # bg=bg1, fg=fg3

# active window title colors
set-window-option -g window-status-current-style bg=red,fg=colour237 # fg=bg1

# pane border
set-option -g pane-active-border-style fg=colour250 #fg2
set-option -g pane-border-style fg=colour237 #bg1

# message infos
set-option -g message-style bg=colour239,fg=colour223 # bg=bg2, fg=fg1

# writing commands inactive
set-option -g message-command-style bg=colour239,fg=colour223 # bg=fg3, fg=bg1

# pane number display
set-option -g display-panes-active-colour colour250 #fg2
set-option -g display-panes-colour colour237 #bg1

# clock
set-window-option -g clock-mode-colour colour109 #blue

# bell
set-window-option -g window-status-bell-style bg=colour167,fg=colour235 # bg=red, fg=bg

## Theme settings mixed with colors (unfortunately, but there is no cleaner way)
set-option -g status-justify "left"
set-option -g status-left-style none
set-option -g status-left-length "80"
set-option -g status-right-style none
set-option -g status-right-length "80"
set-window-option -g window-status-separator ""

set-option -g status-left "#[bg=colour241,fg=colour248] #S #[bg=colour237,fg=colour241,nobold,noitalics,nounderscore]"
set-option -g status-right "#[bg=colour237,fg=colour239 nobold, nounderscore, noitalics]#[bg=colour239,fg=colour246] %Y-%m-%d  %H:%M #[bg=colour239,fg=colour248,nobold,noitalics,nounderscore]#[bg=colour248,fg=colour237] #h "

set-window-option -g window-status-current-format "#[bg=colour214,fg=colour237,nobold,noitalics,nounderscore]#[bg=colour214,fg=colour239] #I #[bg=colour214,fg=colour239,bold] #W#{?window_zoomed_flag,*Z,} #[bg=colour237,fg=colour214,nobold,noitalics,nounderscore]"
set-window-option -g window-status-format "#[bg=colour239,fg=colour237,noitalics]#[bg=colour239,fg=colour223] #I #[bg=colour239,fg=colour223] #W #[bg=colour237,fg=colour239,noitalics]"

# vim: set ft=tmux tw=0 nowrap:
